Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/ClassAndModuleChildren:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/AndOr:
  EnforcedStyle: conditionals
Style/Not:
  Enabled: false
AllCops:
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'spec/spec_helper.rb'
  - 'vendor/**/*'
